### PR TITLE
[device-wallet] fixes #114 - Button ACK in SkycoinSign message

### LINKED ISSUE #114: React to button message in Skycoin sign
**Feature description**

React to button message in Skycoin sign text function

**Is your feature request related to a problem? Please describe.**
If emulator asks for confirmation to sign message , it sends button request. JS library considers this an unexpected message and fails. Emulator does not respond .

**Describe the solution you'd like**
Process this case in `skycoinSignHander` .

**Additional context**
Needed for skycoin/hardware-wallet#77

### PR DESCRIPTION
**Pull request by stdevStark**
Fixes #114 

Changes:
-  Handle case messages.MessageType.MessageType_ButtonRequest in devSkycoinSignMessage

Does this change need to mentioned in CHANGELOG.md?
no

Requires changes in protobuff specs?
no

Requires testing
yes

not needed new tests 

Related issues:

PR skycoin/hardware-wallet#213 for issue skycoin/hardware-wallet#77

### CODE REVIEW

**Comment by stdevStark** [comment]
@olemis what can be [this error](https://travis-ci.com/skycoin/hardware-wallet-js/builds/110630610#L2503-L2514) ?

**Comment by olemis** [comment]
> @olemis what can be [this error](https://travis-ci.com/skycoin/hardware-wallet-js/builds/110630610#L2503-L2514) ?

I restarted the build and everything is ok .

**Comment by stdevStark** [comment]
> I restarted the build and everything is ok .

I can see it now . Not fixed .

**Comment by olemis** [comment]
> I can see it now . Not fixed .

486043c should fix it ... let's wait for Travis .

**Pull request merged**
