### PR TITLE
Transactions-Js

### PR DESCRIPTION
**Pull request by mpsido**
Fixing issue skycoin/hardware-wallet#38

### CODE REVIEW

**Comment by mpsido** [comment]
@Senyoret1 I did my best to finish the test case but there is still a "timeout" problem.

to run the test 
```
 node test/transaction-test.js
```

Even if I press button on emulator as fast as I can the test case timeout and fails.
It should be a configurable option somewhere in the test library, but every time I google it I find mostly source code using mocha.

Maybe we should switch to that test library but I don't have time today to do that.

**Comment by olemis** [comment]
@mpsido can you share the URL of the web page talking about mocha ?

**Comment by mpsido** [comment]
> @mpsido can you share the URL of the web page talking about mocha ?

https://mochajs.org/

**Comment by mpsido** [comment]
image

**Comment by olemis** [comment]
@mpsido oh , I see ... I thought it was one specific to the Trezor emulator . 👍

**Comment by olemis** [comment]
@mpsido @Senyoret1 maybe @stdevHan has some time to take a look into this today. Let you know .

**Comment by Senyoret1** [comment]
> 
> 
> @mpsido @Senyoret1 maybe @stdevHan has some time to take a look into this today. Let you know .

:+1:

**Pull request merged**
