### PR TITLE
fixes #59 - Create a device label

### LINKED ISSUE #59: create a device label
**Feature description**
Be able to define a device label to identify it.

**Describe the solution you'd like**
In the current message `ApplySettings`/`Features` send/receive the device label.

**Describe alternatives you've considered**
Create a new message for send the label or use `ApplySettings`.

Related to https://github.com/skycoin/hardware-wallet/issues/32

### PR DESCRIPTION
**Pull request by stdevAlDen**
Fixes #59 

Changes:
- Add a `deviceLabel` param to `devApplySettings` function.

Does this change need to mentioned in CHANGELOG.md?
yes

Requires testing
yes

### CODE REVIEW

**Comment by olemis** [comment]
@stdevIvr we need #28 to finally merge this .

@Senyoret1 if you need this badly for implementing labels in the desktop wallet , let me know if it's worth closing this (manually tested) and implement this in #28 itself .

**Comment by olemis** [comment]
> @stdevIvr we need #28 to finally merge this .

[Build failure](https://travis-ci.com/skycoin/hardware-wallet-js/builds/101709851#L717-L720) looks like caused by emulator waiting for button press . 

BTW , @stdevAlDen , why is it displaying this `Skycoin hardware NOT FOUND, using emulator` ? Shouldn't it just use emulator right away ?

**Comment by Senyoret1** [comment]
@olemis I need this, but not necessarily "right now". Also, I don't underestand how this could be implemented in https://github.com/skycoin/hardware-wallet-js/issues/28

**Comment by jdknives** [comment]
@olemis please elaborate how the emulator is relevant for this issue.

**Comment by olemis** [comment]
> @olemis I need this, but not necessarily "right now". Also, I don't underestand how this could be implemented in #28

@Senyoret1 my mistake , I was talking of skycoin/hardware-wallet#28 .

**Comment by olemis** [comment]
> @olemis please elaborate how the emulator is relevant for this issue.

test code times out on Travis

**Comment by stdevIvr** [comment]
@olemis I think it's ready for merge. Travis is OK.

**Pull request merged**
