### PR TITLE
replace secure-random by randombytes fixes #65

### LINKED ISSUE #65: Set user host device entropy to the hardware-wallet to be combined with internal hw entropy
**Feature description**
Combine internal hw device entropy with the host one.

**Is your feature request related to a problem? Please describe.**
Related to skycoin/hardware-wallet#88

**Describe the solution you'd like**
Send entropy to the device before call `GenerateMnemonic`

**Describe alternatives you've considered**
Other alternative could be request entropy from the device, but as the protocol implementation is not working with a call/call_back scheme this can make ugly the implementation.

### PR DESCRIPTION
**Pull request by olemis**
Fixes #65 

Changes:
- `randombytes` superseded `secure-random`

Does this change need to mentioned in CHANGELOG.md?
no

Requires testing
no

### CODE REVIEW

**Comment by Senyoret1** [comment]
This code is right on the frontier between what I know and what I do not, so I’m not sure about some details, but there are some things that should probably be verified:

- The call to `secureRandom.randomUint8Array` was directly replaced with `randomBytes`, but the thing is that `secureRandom.randomUint8Array` return an array with numbers and `randomBytes` a bufer. I have done some tests sending crazy data to the hardware wallet and it often accepts them without problems and responds as if the operation had been carried out correctly (but the result is not the expected one), so it would probable be good to check, until being totally sure, if the hardware wallet is really getting what it expect.

- The entropy is being sent to `messages.GenerateMnemonic`, but should it not be sent to `messages.GetEntropy` or `messages.EntropyRequest`?

**Comment by gz-c** [comment]
> I have done some tests sending crazy data to the hardware wallet and it often accepts them without problems and responds as if the operation had been carried out correctly (but the result is not the expected one), so it would probable be good to check, until being totally sure, if the hardware wallet is really getting what it expect.

Can you explain further what kind of data, to what message/endpoint, and open an issue? The hw wallet should not be performing actions on arbitrary data

**Comment by stdevAlDen** [comment]
> This code is right on the frontier between what I know and what I do not, so I’m not sure about some details, but there are some things that should probably be verified:
> 
> * The call to `secureRandom.randomUint8Array` was directly replaced with `randomBytes`, but the thing is that `secureRandom.randomUint8Array` return an array with numbers and `randomBytes` a bufer. I have done some tests sending crazy data to the hardware wallet and it often accepts them without problems and responds as if the operation had been carried out correctly (but the result is not the expected one), so it would probable be good to check, until being totally sure, if the hardware wallet is really getting what it expect.

@Senyoret1 
The buffer data type in C dos not exist, but you can make an array of `uint8_t` or `char` as these can keep bytes and taking a pointer to this array is considered a buffer.

In a [previous firmware implementation](https://github.com/skycoin/hardware-wallet/blob/a5192085619fcc7e488ff607777ed1ece1c8aead/tiny-firmware/firmware/entropy.c#L114-L122) there was some constraints for external entropy, even [with tests](https://github.com/skycoin/hardware-wallet/blob/a5192085619fcc7e488ff607777ed1ece1c8aead/tiny-firmware/firmware/test_fsm.c#L112) but it was removed in https://github.com/skycoin/hardware-wallet/issues/121, so anything received is considered to be ok.

From the js side what I can find is in the `ts` source code(node_modules/@types/node/index.d.ts):
```ts
// Buffer class
type BufferEncoding = "ascii" | "utf8" | "utf16le" | "ucs2" | "base64" | "latin1" | "binary" | "hex";
interface Buffer extends Uint8Array {
    write(string: string, offset?: number, length?: number, encoding?: string): number;
```
`Buffer` is a specialization of `Uint8Array` and so according to what I can find through the internet so far now this is for better compativility in brosers with existing code before es6 but I prefer your feedback about this as I'm not a javascript expert.
> * The entropy is being sent to `messages.GenerateMnemonic`, but should it not be sent to `messages.GetEntropy` or `messages.EntropyRequest`?

The external entropy is send in `messages.EntropyAck` in response to a `messages.EntropyRequest` at least it's how this have to be.
[`messages.GetEntropy`](https://github.com/skycoin/hardware-wallet-protob/blob/c3266da30b9de27ddc2e08f762a386bb2dd5a5d6/protob/messages/messages.proto#L26) is a `in` msg, it means that the device will receive it and the response come on [`MessageType_Entropy`](https://github.com/skycoin/hardware-wallet-protob/blob/c3266da30b9de27ddc2e08f762a386bb2dd5a5d6/protob/messages/messages.proto#L27) this is very usseful to get internal entropy and solve this https://github.com/skycoin/hardware-wallet/issues/105
Note that some minor change can come from https://github.com/skycoin/hardware-wallet-js/issues/81.

Please sorry for be so late in the response but I missed the message, anotatin my user can make a better notification, and you can be sure thet this kind of question is always welcome as this inprove the health of our project.

**Comment by Senyoret1** [comment]
@stdevAlDen sorry for the late response.
 
About the first point, my concern was if the JavaScript buffer type was being correctly converted to the type expected by C. In fact, JavaScript could simply be sending a string containing `"<buffer>"`.

I saw that when running `npm run make-protobuf-files` the generated `skycoin.js` file contains type limitations. I mean, if a message is suposed to receive a boolean value, the javascript value must be boolean or an error is thrown. Knowing that, it seemed strange that the `messages.GenerateMnemonic.create()` function can receive arrays and buffers.

I investigated a little more and saw that, in fact, the `GenerateMnemonic` message does not have an `entropy` parameter:
https://github.com/skycoin/hardware-wallet-protob/blob/c3266da30b9de27ddc2e08f762a386bb2dd5a5d6/protob/messages/messages.proto#L127-L129

Due to that, the JS code does not check if the entropy is send using a valid data type and probably it does not correctly encode the data either. The message that has an `entropy` property is `EntropyAck`:
https://github.com/skycoin/hardware-wallet-protob/blob/c3266da30b9de27ddc2e08f762a386bb2dd5a5d6/protob/messages/messages.proto#L381-L388

Looking at that, I think I now know more precisely were could be a problem:
https://github.com/skycoin/hardware-wallet-js/blob/953ffc86f075de0e514d5a2f2c380ac59aac90d8/device-wallet.js#L328-L335 

In that code segment the `messages.MessageType.MessageType_EntropyAck` is used in line 333, which should be fine, but the msg and the buffer are created with `messages.GenerateMnemonic` in lines 331 and 332, instead of `messages.EntropyAck`, which does not seem to be right. If you see the neighboring functions, the message and buffer are always created with the functions corresponding to the message used:
https://github.com/skycoin/hardware-wallet-js/blob/953ffc86f075de0e514d5a2f2c380ac59aac90d8/device-wallet.js#L312-L344

@olemis @therealssj maybe it would be good idea to check if something similar is being done in the Go code.

**Comment by olemis** [comment]
>     * The entropy is being sent to `messages.GenerateMnemonic`, but should it not be sent to `messages.GetEntropy` or `messages.EntropyRequest`?

As @gz-c suggested (I can't find where exactly) external entropy is always mixed with internal entropy. Hence the sequence of events is like this .

- invoke method ( e.g. `GenerateMnemonic` )
- firmware will reply with `EntropyRequest` msg
- {js,go} library replies with `EntropyAck` msg
- firmware mixes external entropy with internal entropy
- repeat method (e.g. `GenerateMnemonic` )

**Comment by olemis** [comment]
> In a [previous firmware implementation](https://github.com/skycoin/hardware-wallet/blob/a5192085619fcc7e488ff607777ed1ece1c8aead/tiny-firmware/firmware/entropy.c#L114-L122) there was some constraints for external entropy, even [with tests](https://github.com/skycoin/hardware-wallet/blob/a5192085619fcc7e488ff607777ed1ece1c8aead/tiny-firmware/firmware/test_fsm.c#L112) but it was removed in [skycoin/hardware-wallet#121](https://github.com/skycoin/hardware-wallet/issues/121), so anything received is considered to be ok.

for the record , we added some changes to filter external entropy buffers based on their measured quantity of information (i.e. Shannon). That's wrong. Change was reverted.

**Pull request merged**
