### PR TITLE
[test] fixes #74 - Refactor promises in test code

### LINKED ISSUE #74: Refactor async test code
**Feature description**

Describe the feature

**Is your feature request related to a problem? Please describe.**
Travis builds ignore silently some test failures .

**Describe alternatives you've considered**
Refactor test code to use a style similar to the one used in `applySettings`.

**Additional context**

**Possible implementation**

- [x] Rewrite test promises code
- ~Remove `rejectPromise` (if possible)~

### PR DESCRIPTION
**Pull request by stdevStark**
Fixes #74 

Changes:
- Apply settings
- Cancel requests
- Device backup
- Generate mnemonic
- Protobuffer messages
- Signing

Does this change need to mentioned in CHANGELOG.md?
no

Requires changes in protobuff specs?
no

Requires testing
no

### CODE REVIEW

**Comment by stdevStark** [comment]
@olemis this is ok . No button to ask a review .

**Comment by olemis** [comment]
There are two errors .

- Test failures e.g. [apply settings test case](https://travis-ci.com/skycoin/hardware-wallet-js/builds/105709658#L2473-L2482) fails
- The Travis build does not fail 

Not ready ...

**Comment by olemis** [comment]
@stdevStark I tried adding an explicit `exit` for `npm test` to fail , but [it still does not report test failure](https://travis-ci.com/skycoin/hardware-wallet-js/builds/106402663) . Any ideas ?

**Comment by stdevStark** [comment]
@olemis this will be completed soon . Only error is [Message signing disabled in formware](https://travis-ci.com/skycoin/hardware-wallet-js/builds/106591833#L3498-L3514) . It depends on skycoin/hardware-wallet#123 . I finish that first or eliminate the test here?

**Comment by olemis** [comment]
> @olemis this will be completed soon . 

The part of failing the build if tests fail is not done yet .

> Only error is [Message signing disabled in formware](https://travis-ci.com/skycoin/hardware-wallet-js/builds/106591833#L3498-L3514) . It depends on [skycoin/hardware-wallet#123](https://github.com/skycoin/hardware-wallet/issues/123) . I finish that first or eliminate the test here?

Keep the test case and finish skycoin/hardware-wallet#123

**Comment by olemis** [comment]
> Only error is [Message signing disabled in formware](https://travis-ci.com/skycoin/hardware-wallet-js/builds/106591833#L3498-L3514) . It depends on [skycoin/hardware-wallet#123](https://github.com/skycoin/hardware-wallet/issues/123) . I finish that first or eliminate the test here?

Message will be kept , pls change the test cases . Setup auto buttons for #77

**Pull request merged**
